server:
  servlet:
    context-path: /api/v1

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: PayMilli
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${db.host}:${db.port}/${db.database}?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: ${db.username}
    password: ${db.password}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        #        dialect: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect
        globally_quoted_identifiers: true
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true

jwt:
  header: Authorization
  secret: ${jwt.secret}
  token-validity-in-seconds: 86400


